# Generated by Django 5.2 on 2025-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelGeneralMetaData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Metadata name")),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Spaces and '-' will be replaced by '_'",
                        max_length=200,
                        null=True,
                        verbose_name="Metadata field name",
                    ),
                ),
                (
                    "meta_type",
                    models.CharField(
                        choices=[
                            ("CharField", "Text"),
                            ("DateField", "Date"),
                            ("DateTimeField", "DateTime"),
                            ("IntegerField", "Integer"),
                            ("DecimalField", "Decimal Number"),
                            ("ForeignKey", "Relation"),
                            ("JSONField", "JSON Data"),
                            ("ChoiceField", "Normal Select"),
                        ],
                        max_length=20,
                        verbose_name="Metadata type",
                    ),
                ),
                ("searchable", models.BooleanField(default=False, verbose_name="Searchable ?")),
                ("widget_attrs", models.JSONField(blank=True, verbose_name="Attributes (JSON Format)")),
            ],
            options={
                "swappable": "DJANGO_MODEL_METADATA_MODELGENERALMETADATA_MODEL",
            },
        ),
    ]
