# Generated by Django 5.2 on 2025-04-13 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_model_metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelgeneralmetadata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelgeneralmetadata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
